### ISSUE TITLE
Having error when inputting the videoID into ytmpl

### ISSUE THREAD

**Issue by lo8888** [patrickkfkan/yt-mix-playlist#2]
I tried executing the example script and I got this error

```
node example.js

Obtaining Mix playlist for video XCcN-IoYIJA...

/home/ubuntu/DiscordBot_v1/node_modules/yt-mix-playlist/lib/parser.js:72
    return txt.simpleText || txt.runs.map(a => a.text).join('');
               ^

TypeError: Cannot read properties of undefined (reading 'simpleText')
    at parseText (/home/ubuntu/DiscordBot_v1/node_modules/yt-mix-playlist/lib/parser.js:72:16)
    at Object.getCollapsedPlaylistInfo (/home/ubuntu/DiscordBot_v1/node_modules/yt-mix-playlist/lib/parser.js:95:29)
    at getCollapsedList (/home/ubuntu/DiscordBot_v1/node_modules/yt-mix-playlist/lib/index.js:51:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getMixPlaylist (/home/ubuntu/DiscordBot_v1/node_modules/yt-mix-playlist/lib/index.js:37:25)
    at async getMixPlaylist (/home/ubuntu/DiscordBot_v1/node_modules/yt-mix-playlist/example/example.js:5:12)
    at async main (/home/ubuntu/DiscordBot_v1/node_modules/yt-mix-playlist/example/example.js:41:14)
```

**Comment by patrickkfkan** [comment]
Does it happen with other video IDs ? I just ran the example with the same video ID and didn't get any error...

**Comment by lo8888** [comment]
I tried that on my local computer and it is fine but I don't know why it is not working on the VPS (running Ubuntu 20.04). Is there anything I need to set up before?

**Comment by patrickkfkan** [comment]
I would first check if it is an issue with your VPS by sending a request to YouTube and inspecting the response.

**Comment by lo8888** [comment]
The response using the example.js is 
```
{ simpleText: 'Mix - Wiljan & Xandra - Woodlands' }
undefined
```

Don't know why is it the case, but the bot can use "ytpl" and "ytdl-core" modules to get songs from user-created playlists.

**Comment by patrickkfkan** [comment]
In `parser.js` -> `getJsonFromBody(body)`, could you check the value of `body` or `json`? At least this will show the data returned by the request.

**Comment by lo8888** [comment]
I got this response for the json
Obtaining Mix playlist for video XCcN-IoYIJA...
```

{
  responseContext: {
    serviceTrackingParams: [ [Object], [Object], [Object], [Object] ],
    mainAppWebResponseContext: { loggedOut: true },
    webResponseContextExtensionData: {
      ytConfigData: [Object],
      webPrefetchData: [Object],
      hasDecorated: true
    }
  },
  contents: {
    twoColumnWatchNextResults: {
      results: [Object],
      secondaryResults: [Object],
      autoplay: [Object]
    }
  },
  currentVideoEndpoint: {
    clickTrackingParams: 'CAAQg2ciEwitpvCtpND1AhVPRHoFHSBpAdc=',
    commandMetadata: { webCommandMetadata: [Object] },
    watchEndpoint: {
      videoId: 'XCcN-IoYIJA',
      watchEndpointSupportedOnesieConfig: [Object]
    }
  },
  trackingParams: 'CAAQg2ciEwitpvCtpND1AhVPRHoFHSBpAdc=',
  playerOverlays: {
    playerOverlayRenderer: {
      endScreen: [Object],
      autoplay: [Object],
      shareButton: [Object],
      addToMenu: [Object],
      videoDetails: [Object],
      decoratedPlayerBarRenderer: [Object]
    }
  },
  onResponseReceivedEndpoints: [
    {
      clickTrackingParams: 'CAAQg2ciEwitpvCtpND1AhVPRHoFHSBpAdc=',
      commandMetadata: [Object],
      signalServiceEndpoint: [Object]
    }
  ],
  engagementPanels: [ { engagementPanelSectionListRenderer: [Object] } ],
  topbar: {
    desktopTopbarRenderer: {
      logo: [Object],
      searchbox: [Object],
      trackingParams: 'CAEQq6wBIhMIrabwraTQ9QIVT0R6BR0gaQHX',
      interstitial: [Object],
      topbarButtons: [Array],
      hotkeyDialog: [Object],
      backButton: [Object],
      forwardButton: [Object],
      a11ySkipNavigationButton: [Object],
      voiceSearchButton: [Object]
    }
  },
  frameworkUpdates: { entityBatchUpdate: { mutations: [Array], timestamp: [Objec                                                                                       t] } }
}
/home/ubuntu/DiscordBot_v1/node_modules/yt-mix-playlist/lib/parser.js:73
    return txt.simpleText || txt.runs.map(a => a.text).join('');
               ^

TypeError: Cannot read properties of undefined (reading 'simpleText')

```
